### ISSUE TITLE
Support passoport style usage.

### ISSUE THREAD

**Issue by Volox** [rickharrison/koa-flash#1]
Hello,
it is possible to support the standard @jaredhanson `connect-flash` usage type? Instead of an object `this.flash` should be a function like:

```js
// Setter
this.flash('info', 'Flash is back!') // Connect style flash
// Getter
this.flash( 'info' );
```

http://passportjs.org/guide/authenticate/

**Comment by rickharrison** [comment]
I'm going to close this as the current API is more in the style of koa.
